name: MLops CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  # 🧩 1️⃣ Data Processing & Feature Engineering
  data_pipeline:
    name: Data Processing & Feature Engineering
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.5'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Data Processing
        run: |
          python src/data/run_processing.py \
            --input data/raw/house_data.csv \
            --output data/processed/cleaned_house_data.csv

      - name: Run Feature Engineering
        run: |
          python src/features/engineer.py \
            --input data/processed/cleaned_house_data.csv \
            --output data/processed/featured_house_data.csv \
            --preprocessor models/trained/preprocessor.pkl

  # 🤖 2️⃣ Model Training (Depende del job anterior)
  model_training:
    name: Model Training with MLflow
    runs-on: ubuntu-latest
    needs: data_pipeline  # 👈 se ejecuta solo si el job anterior tuvo éxito

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.5'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Setup MLflow
        run: |
          docker pull ghcr.io/mlflow/mlflow:latest
          docker run -d --name mlflow-server -p 5555:5000 ghcr.io/mlflow/mlflow:latest \
            mlflow server --host 0.0.0.0 \
            --backend-store-uri sqlite:///mlflow.db \
            --default-artifact-root /tmp/mlruns

      - name: Train Models
        run: |
          python src/models/train_model.py \
            --config configs/model_config.yaml \
            --data data/processed/featured_house_data.csv \
            --models-dir models \
            --mlflow-tracking-uri http://localhost:5555

      - name: Clean up MLflow
        run: |
          docker stop mlflow-server
          docker rm mlflow-server
          docker rmi ghcr.io/mlflow/mlflow:latest

  # 🐳 3️⃣ Docker Build & Push (Depende del entrenamiento)
  docker_deploy:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    needs: model_training  # 👈 se ejecuta solo si el entrenamiento fue exitoso

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: javiercamilogarcia/fastapi:${{ github.sha }}
          context: .
          file: Dockerfile


