name: MLops CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  
jobs:
  workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@2

      - name: Set up Python
        uses: actions/setup-python@2
        with:
          python-version: '3.11.5'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest tests/

